In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("insurance_claim_fraud_dataset.csv")

In [3]:
print("Shape:", df.shape)

Shape: (100000, 62)

In [4]:
print("First 5 records:")
display(df.head())

First 5 records:

,claim_id,policy_id,customer_id,customer_name,claim_date,incident_date,claim_status,claim_amount,approved_amount,deductible,...,identity_verified,claim_history_risk,fraud_risk_score,repair_cost,medical_cost,towing_cost,rental_vehicle_cost,total_loss,payout_amount,fraudulent
0,CLM-0000001,POL-75682867,CUST-231932,Allison Hill,2024-09-01,2024-08-25,Denied,7909.06,0.00,250.0,...,Yes,Medium,38,7044.74,0.00,0.00,864.32,No,0.00,Yes
1,CLM-0000002,POL-79778859,CUST-356508,Noah Rhodes,2022-02-08,2022-02-06,Denied,12676.05,11408.44,1000.0,...,Yes,Medium,2,12370.73,0.00,149.52,155.80,Yes,11676.05,No
2,CLM-0000003,POL-93122310,CUST-894824,Angie Henderson,2025-10-29,2025-10-29,Approved,14930.34,14930.34,1000.0,...,Yes,Low,0,3002.83,10517.48,335.54,1074.49,No,13930.34,No
3,CLM-0000004,POL-63892568,CUST-668550,Daniel Wagner,2021-11-14,2021-11-14,Pending,1018.98,917.08,1000.0,...,Yes,Low,0,1018.98,0.00,0.00,0.00,No,18.98,No
4,CLM-0000005,POL-50657662,CUST-792517,Cristian Santos,2024-10-02,2024-10-01,Denied,20924.38,18831.94,250.0,...,Yes,Medium,3,20205.57,0.00,202.14,516.67,No,20674.38,No

In [5]:
print("Last 5 records:")
display(df.tail())

Last 5 records:

,claim_id,policy_id,customer_id,customer_name,claim_date,incident_date,claim_status,claim_amount,approved_amount,deductible,...,identity_verified,claim_history_risk,fraud_risk_score,repair_cost,medical_cost,towing_cost,rental_vehicle_cost,total_loss,payout_amount,fraudulent
99995,CLM-0099996,POL-86723000,CUST-287217,Christine King,2025-04-12,2025-04-11,Denied,10353.30,9317.97,500.0,...,Yes,Low,1,6789.70,1981.43,418.39,1163.78,No,9853.30,No
99996,CLM-0099997,POL-46790146,CUST-553403,George Richardson,2024-02-26,2024-02-24,Pending,2730.41,2457.37,1000.0,...,Yes,Low,12,2397.68,0.00,0.00,332.73,No,1730.41,No
99997,CLM-0099998,POL-80965038,CUST-805809,Michael Shaw,2021-11-28,2021-11-25,Closed,7018.66,6316.79,500.0,...,Yes,Medium,3,6374.40,0.00,0.00,644.26,No,6518.66,No
99998,CLM-0099999,POL-52875571,CUST-915203,Tracy Johnson,2024-06-28,2024-06-24,Pending,7691.45,6922.31,1000.0,...,Yes,Medium,11,6497.97,932.60,83.58,177.30,Yes,6691.45,No
99999,CLM-0100000,POL-70029478,CUST-836345,Tonya Lewis,2021-09-09,2021-09-09,Denied,1298.52,0.00,2500.0,...,Yes,Low,29,1298.52,0.00,0.00,0.00,No,0.00,Yes

In [7]:
print(df.columns.tolist())

['claim_id', 'policy_id', 'customer_id', 'customer_name', 'claim_date', 'incident_date', 'claim_status', 'claim_amount', 'approved_amount', 'deductible', 'claim_duration_days', 'age', 'gender', 'marital_status', 'occupation', 'annual_income', 'education_level', 'credit_score', 'years_with_company', 'previous_claims', 'policy_type', 'policy_start_date', 'policy_duration_years', 'premium_amount', 'coverage_amount', 'deductible_plan', 'payment_method', 'policy_active', 'incident_type', 'accident_severity', 'incident_location', 'weather_condition', 'police_report', 'witnesses', 'injuries', 'hospital_visit', 'property_damage', 'vehicle_damage', 'vehicle_make', 'vehicle_model', 'vehicle_year', 'vehicle_age', 'mileage', 'vehicle_value', 'ownership_type', 'suspicious_documents', 'claim_submitted_at_night', 'multiple_claims_last_year', 'delayed_reporting', 'inconsistent_statements', 'gps_location_match', 'repair_shop_verified', 'identity_verified', 'claim_history_risk', 'fraud_risk_score', 'repair_cost', 'medical_cost', 'towing_cost', 'rental_vehicle_cost', 'total_loss', 'payout_amount', 'fraudulent']

In [8]:
print(df.dtypes)

claim_id                object
policy_id               object
customer_id             object
customer_name           object
claim_date              object
                        ...
towing_cost            float64
rental_vehicle_cost    float64
total_loss              object
payout_amount          float64
fraudulent              object
Length: 62, dtype: object

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 62 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   claim_id                   100000 non-null  object
 1   policy_id                  100000 non-null  object
 2   customer_id                100000 non-null  object
 3   customer_name              100000 non-null  object
 4   claim_date                 100000 non-null  object
 5   incident_date              100000 non-null  object
 6   claim_status               100000 non-null  object
 7   claim_amount               100000 non-null  float64
 8   approved_amount            100000 non-null  float64
 9   deductible                 100000 non-null  float64
 10  claim_duration_days        100000 non-null  int64
 11  age                        100000 non-null  int64
 12  gender                     100000 non-null  object
 13  marital_status             100000 non-null  object
 14  occupation                 100000 non-null  object
 15  annual_income              100000 non-null  float64
 16  education_level            100000 non-null  object
 17  credit_score               100000 non-null  int64
 18  years_with_company         100000 non-null  int64
 19  previous_claims            100000 non-null  int64
 20  policy_type                100000 non-null  object
 21  policy_start_date          100000 non-null  object
 22  policy_duration_years      100000 non-null  int64
 23  premium_amount             100000 non-null  float64
 24  coverage_amount            100000 non-null  float64
 25  deductible_plan            100000 non-null  object
 26  payment_method             100000 non-null  object
 27  policy_active              100000 non-null  object
 28  incident_type              100000 non-null  object
 29  accident_severity          100000 non-null  object
 30  incident_location          100000 non-null  object
 31  weather_condition          100000 non-null  object
 32  police_report              100000 non-null  object
 33  witnesses                  100000 non-null  int64
 34  injuries                   100000 non-null  int64
 35  hospital_visit             100000 non-null  object
 36  property_damage            100000 non-null  object
 37  vehicle_damage             83473 non-null   object
 38  vehicle_make               100000 non-null  object
 39  vehicle_model              100000 non-null  object
 40  vehicle_year               100000 non-null  int64
 41  vehicle_age                100000 non-null  int64
 42  mileage                    100000 non-null  int64
 43  vehicle_value              100000 non-null  float64
 44  ownership_type             100000 non-null  object
 45  suspicious_documents       100000 non-null  object
 46  claim_submitted_at_night   100000 non-null  object
 47  multiple_claims_last_year  100000 non-null  object
 48  delayed_reporting          100000 non-null  object
 49  inconsistent_statements    100000 non-null  object
 50  gps_location_match         100000 non-null  object
 51  repair_shop_verified       100000 non-null  object
 52  identity_verified          100000 non-null  object
 53  claim_history_risk         100000 non-null  object
 54  fraud_risk_score           100000 non-null  int64
 55  repair_cost                100000 non-null  float64
 56  medical_cost               100000 non-null  float64
 57  towing_cost                100000 non-null  float64
 58  rental_vehicle_cost        100000 non-null  float64
 59  total_loss                 100000 non-null  object
 60  payout_amount              100000 non-null  float64
 61  fraudulent                 100000 non-null  object
dtypes: float64(12), int64(12), object(38)
memory usage: 47.3+ MB

In [12]:
print(df.isnull())

       claim_id  policy_id  customer_id  customer_name  claim_date  \
0         False      False        False          False       False
1         False      False        False          False       False
2         False      False        False          False       False
3         False      False        False          False       False
4         False      False        False          False       False
...         ...        ...          ...            ...         ...
99995     False      False        False          False       False
99996     False      False        False          False       False
99997     False      False        False          False       False
99998     False      False        False          False       False
99999     False      False        False          False       False

       incident_date  claim_status  claim_amount  approved_amount  deductible  \
0              False         False         False            False       False
1              False         False         False            False       False
2              False         False         False            False       False
3              False         False         False            False       False
4              False         False         False            False       False
...              ...           ...           ...              ...         ...
99995          False         False         False            False       False
99996          False         False         False            False       False
99997          False         False         False            False       False
99998          False         False         False            False       False
99999          False         False         False            False       False

       ...  identity_verified  claim_history_risk  fraud_risk_score  \
0      ...              False               False             False
1      ...              False               False             False
2      ...              False               False             False
3      ...              False               False             False
4      ...              False               False             False
...    ...                ...                 ...               ...
99995  ...              False               False             False
99996  ...              False               False             False
99997  ...              False               False             False
99998  ...              False               False             False
99999  ...              False               False             False

       repair_cost  medical_cost  towing_cost  rental_vehicle_cost  \
0            False         False        False                False
1            False         False        False                False
2            False         False        False                False
3            False         False        False                False
4            False         False        False                False
...            ...           ...          ...                  ...
99995        False         False        False                False
99996        False         False        False                False
99997        False         False        False                False
99998        False         False        False                False
99999        False         False        False                False

       total_loss  payout_amount  fraudulent
0           False          False       False
1           False          False       False
2           False          False       False
3           False          False       False
4           False          False       False
...           ...            ...         ...
99995       False          False       False
99996       False          False       False
99997       False          False       False
99998       False          False       False
99999       False          False       False

[100000 rows x 62 columns]

In [13]:

print(df.isnull().sum())

claim_id               0
policy_id              0
customer_id            0
customer_name          0
claim_date             0
                      ..
towing_cost            0
rental_vehicle_cost    0
total_loss             0
payout_amount          0
fraudulent             0
Length: 62, dtype: int64

In [15]:
print(df.duplicated().sum())

0